### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by TimOetting** [mmende/spectro#1]
Hey Martin,

are you somehow still working on this package? I was searching for a way to draw a spectrogram via nodeJS and stumbled upon the spectro package. 

I tried out the example, but it seems not to handle the entire wav file. the _data_ event callback is executed exactly 30 times, no matter how large the file is. The fileRead property is never set to true and because of that the example code never draws the image. Calling audioFile.read() inside the callback of the audioFile's _readable_ event seems to help with this. The script, however, seems not to handle the file up to the end.

You see, there are some issues that I was not able to fix after some hours of researching. So, let me just know if you have plans to put some work into this repo or if you have some hints how to make it work.

Thanks a lot,
Tim

**Comment by mmende** [comment]
Hm strange ... did you use the test files from the audios directory or own ones? The package will at least only work with pcm data... Kind regards

**Comment by mmende** [comment]
Thanks for the contribution
